config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/v1"
  end

  # post 'groups/fork'
  # resources :groups

  # get 'tasks/done'
  # post 'tasks/status_change'
  get 'tasks/importance'
  # resources :tasks

  # get 'pages/page'

  post 'endpoints/register'
  get 'endpoints/getVapidPublicKey'

  #ルート
  # root 'tasks#index'

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   post "sign_in", :to => "users/sessions#create"
  #   get "sign_out", :to => "users/sessions#destroy" 
  # end

  scope :v1, defaults: { format: :json } do
    post '/', to: 'graphql#execute'

    devise_for :users, :path => '', controllers: {
      :omniauth_callbacks => 'users/omniauth_callbacks',
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
    }

    devise_scope :user do
      get 'user', to: 'users/sessions#show'
      post 'sign_up', to: 'users/registrations#create'
      post 'confirm', to: 'users/confirmations#confirm'
      post 'reset', to: 'users/passwords#reset'
      post 'redirect', to: 'users/omniauth_callbacks#redirect'
      post 'callbacklogin', to: 'users/omniauth_callbacks#callbacklogin'
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, presence: true
    belongs_to :group
    has_many :contributions, dependent: :destroy
    enum status: { todo: 1, doing: 2, done: 3 }

    scope :finished, -> { where.not(finish_time: nil) }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:importance]

  include Pixela
  include GroupUtil

  # GET /tasks
  # GET /tasks.json
  def index

    if current_user.sign_in_count.zero?
      group = Group.create(
        name: "general",
        user_id: current_user.id
      )
      
      group.save
    end

    if params['q'].nil?
      @tasks = Task.where(user_id: current_user.id).order('priority DESC')
    end
    @q = Task.where(user_id: current_user.id).order('priority DESC').ransack(params[:q])
    @tasks = @q.result(distinct: true)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    #5分タイマーを作動させるフラグ
    if (params[:timer] == '1')
      @timer = 1;
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end 

  # GET /tasks/1/edit
  def edit
  end

  # GET /tasks/done
  def done
    @tasks = Task.where(user_id: current_user.id).order('finish_time DESC')
    @graph = get_graph
  end

  # GET /tasks/importance
  def importance
    if params[:limit]
      limit = params[:limit].to_i
    else
      limit = 1
    end
    
    importance = Task.where(user_id: params[:id].to_i, status: 1).order('importance DESC, urgency DESC').limit(limit)

    render :json => importance
    # redirect_to controller: 'tasks', action: 'show', id: importance.id, timer: 1
  end

  # POST /tasks
  # POST /tasks.json
  def create
    #task_data = {}
    #task_data.merge!(task_params)
    #task_data['user_id'] = current_user.id
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def tweet(text)
    twitter_client.update(text)
  end

  def status_change
    @task = Task.find(params[:id])
    if @task.status == 1
      @task.start_time = Time.zone.now
      @task.status += 1

      if Oauth.where(user_id: current_user.id)[0]
        # tweetText = "今から頑張って、タスクに取り組みます！\n応援してください!\n完了報告をお楽しみに！#Folivora"
        # tweet(tweetText)
      end

    elsif @task.status == 2
      @task.finish_time = Time.zone.now
      @task.status += 1
      save_commitment(Time.gm(2018, 8, 17))

      if Oauth.where(user_id: current_user.id)[0]
        # tweetText = "タスクおわりました！\n応援ありがとうございました!\n#Folivora"
        # tweet(tweetText)
      end

    end

    @task.save
    #redirect_to :action => "index"
    redirect_to controller: 'tasks', action: 'show', id: @task.id
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  helper_method :get_ancestor_groups

  private
  def twitter_client
    @oauth = Oauth.where(user_id: current_user.id)[0]
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['TWITTER_CONSUMER_KEY']
      config.consumer_secret = ENV['TWITTER_CONSUMER_SECRET']
      config.access_token = @oauth.access_token
      config.access_token_secret = @oauth.access_token_secret
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    deadline = Date.new(params['task']["deadline(1i)"].to_i, params['task']["deadline(2i)"].to_i, params['task']["deadline(3i)"].to_i)
    diff = (deadline - Date.today).to_i
    urgency = 5

    if diff == 0
      urgency = 5
    elsif diff < 3
      urgency = 4
    elsif diff >= 3 && diff <= 31
      urgency = 3
    elsif diff > 31 && diff <= 62
      urgency = 2
    elsif diff > 62
      urgency = 1
    end

    priority = params['task']['importance'].to_i * urgency

    if params['task'].key?('id')
      params['task']['user_id'] = Task.find(params['task']['id']).user_id
    else
      params['task']['user_id'] = current_user.id
    end

    params['task']['urgency'] = urgency
    params['task']['priority'] = priority

    params.require(:task).permit(:name, :deadline, :importance, :note, :status, :start_time, :finish_time, :user_id, :urgency, :priority, :group_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :タスク名 %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="field">
    <%= form.label :締め切り %>
    <%= form.datetime_select :deadline, id: :task_deadline %>
  </div>

  <div class="field">
    <%= form.label :重要度 %>
    <%= form.select :importance, [["☆", 1],["☆☆", 2], ["☆☆☆", 3], ["☆☆☆☆", 4], ["☆☆☆☆☆", 5]] %>
  </div>

  <div class="field">
    <%= form.label :メモ %>
    <%= form.text_area :note, id: :task_note %>
  </div>

  <div class="field">
    <%= form.label :グループ %>
    <%#%= form.number_field :parent_id, id: :group_parent_id %>
    <%= form.collection_select :group_id, Group.where('user_id': current_user.id), :id, :name %>
  </div>

  <div class="field">
    <%= form.label :進捗 %>
    <%= form.select :status, [["TODO", 1],["DOING", 2], ["DONE", 3]] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/done.html.erb
<div class="container done">
  <h1>活動サマリ</h1>
  <section class="graph">
    <h2>頑張りグラフ</h2>
    <%= @graph.html_safe %>
  </section>
  <div class="boards">
    <section class="board done">
      <h2>DONE</h2>
      <ul>
        <% @tasks.each do |task| %>
        <% if task.status == 3 %>
        <li class="card">
          <%= link_to(task) do %>
          <div class="card_header">
            <h3>
              <%= task.name %>
              <span class="stars">
                <%= "★" * task.importance %>
              </span>
            </h3>
          </div>
          <% end %>
          <div class="card_body">
            <p><%= task.note %></p>
          </div>
          <div class="card_footer">

          </div>
        </li>
        <% end %>
        <% end %>
      </ul>
    </section>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
	<% if @task.user_id == current_user.id %>

		<h1>タスクを編集する</h1>

		<%= render 'form', task: @task %>

		<%= link_to 'タスクを表示', @task %> |
		<%= link_to 'タスク一覧に戻る', tasks_path %>
	</div>
  <% else %>
    <div class="attention">
      <i class="fas fa-exclamation-circle"></i>
        <p>タスクへのアクセス権がありません。</p>
        <%= link_to 'タスク一覧へ戻る', tasks_path %>
    </div>
  <% end %>

app/views/tasks/index.html.erb
<% content_for :manifest do %>
	<link rel="manifest" href="manifest.json"/>
	<%= javascript_include_tag '/sw/serviceworker.js' %>
	<%= javascript_include_tag 'timer.js' %>
<% end %>
<% content_for :title do %>
	ホーム
<% end %>
<% content_for :search do %>
	<%= search_form_for @q do |f| %>
		<div class="search_form">
			<%= f.search_field :name_cont %>
			<i class="fas fa-search"></i>
		</div>
	<% end %>
<% end %>


<div class="container">
	<h1>ホーム</h1>
	<p id="notice"><%= notice %></p>

<!-- 	<% if params[:q] %>
		<% if @tasks.nil? %>
			<p>なかったよ</p>
		<% else %>
			<p>あったよ</p>
		<% end %>
	<% end %> -->
	<div class="boards">
		<%= render 'application/task_board', status: 1, tasks: @tasks %>
		<%= render 'application/task_board', status: 2, tasks: @tasks %>
	</div>
</div>
<%= render 'application/task_create_button' %>

app/views/tasks/new.html.erb
<div class="container">
<h1>新しいタスクを作る</h1>

<%= render 'form', task: @task %>

<%= link_to 'タスク一覧へ戻る', tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container" id="overlay">
  <% if @task.user_id == current_user.id %>
    <div class="task">
      <p id="notice"><%= notice %></p>

      <h1><%= @task.name %>
        <% if @task.status == 1%>
          <span class="status todo">
            TODO
          </span>
        <% elsif @task.status == 2%>
          <span class="status doing">
            DOING
          </span>
        <% else @task.status == 3%>
          <span class="status done">
            DONE
          </span>
        <% end %>
      </h1>

      <ul>
        <li><span class="stars"><%= "★" * @task.importance %></span></li>
        <li>締め切り: <%= @task.deadline %></li>
        <li>メモ: <%= @task.note %></li>
        <li>始めた時刻: <%= @task.start_time %></li>
        <li>終わった時刻: <%= @task.finish_time %></li>
      </ul>

      <%= link_to 'タスクを編集する', edit_task_path(@task) %> |
      <%= link_to 'タスク一覧へ戻る', tasks_path %>
    </div>
    <%= javascript_include_tag 'audio.js' %>
  <% else %>
    <div class="attention">
      <i class="fas fa-exclamation-circle"></i>
        <p>タスクへのアクセス権がありません。</p>
        <%= link_to 'タスク一覧へ戻る', tasks_path %>
    </div>
  <% end %>
  <%= javascript_include_tag('timer.js', 'overlay.js') %>
  <input type="button" id="start" value="スタート" onclick="cntStart();">
  
</div>

<% if @timer == 1 then %>
  <script>
    window.onload = function(){
      var time = document.getElementById("start");
      time.click();
    }
  </script>
<% end %>

  <div class="timer" id="timer">
  <h1>とりあえず5分「<%= @task.name %>」をやっていこう！</h1>
    <form name="timer">
      <%= label_tag("残り時間:") %>
      <input type="text" value="5">分
      <input type="text" value="0">秒<br>
      <input type="button" id="stop" value="ストップ" onclick="cntStop()">
    </form>
  </div>

  <!--  
        <%= label_tag("残り時間:") %>
        <%= text_field_tag 'timer', "5" %>分
        <%= text_field_tag 'timer', "0" %>秒
        <%= link_to 'スタート', 'javascript:void(0);', onclick: "cntStart()" %>
        <%= link_to 'ストップ', 'javascript:void(0);', onclick: "cntStop()" %>
        <%= link_to 'リセット', 'javascript:void(0);', onclick: "reSet()" %>
  -->    