config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/v1"
  end

  # post 'groups/fork'
  # resources :groups

  # get 'tasks/done'
  # post 'tasks/status_change'
  get 'tasks/importance'
  # resources :tasks

  # get 'pages/page'

  post 'endpoints/register'
  get 'endpoints/getVapidPublicKey'

  #ルート
  # root 'tasks#index'

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   post "sign_in", :to => "users/sessions#create"
  #   get "sign_out", :to => "users/sessions#destroy" 
  # end

  scope :v1, defaults: { format: :json } do
    post '/', to: 'graphql#execute'

    devise_for :users, :path => '', controllers: {
      :omniauth_callbacks => 'users/omniauth_callbacks',
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
    }

    devise_scope :user do
      get 'user', to: 'users/sessions#show'
      post 'sign_up', to: 'users/registrations#create'
      post 'confirm', to: 'users/confirmations#confirm'
      post 'reset', to: 'users/passwords#reset'
      post 'redirect', to: 'users/omniauth_callbacks#redirect'
      post 'callbacklogin', to: 'users/omniauth_callbacks#callbacklogin'
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/page.html.erb
<h1>通知試験地</h1>

<p>Find me in app/views/pages/page.html.erb</p>

<script>
function notify(message, url) {
    if (!("Notification" in window)) {
        alert("ブラウザが未対応です");
    } else if (Notification.permission === "granted") {
        // 通知が許可されているか確認し、許可されていれば通知を出す
        makeNotification(message, url);
    } else if (Notification.permission !== 'denied') {
        // 通知がまだ許可されていなかった場合に許可を求める
        Notification.requestPermission(function (permission) {
            //ユーザが許可したら通知を出す
            if (permission === "granted") {
                makeNotification(message, url);
            }
        });
    }
}

function makeNotification(message, url) {
    console.log(url)
    var notification = new Notification("タスクドライバー", {body: message});
    notification.onclick = function () {
        notification.close();
        window.open(url);
    };
}
</script>

<input type="button" value="通知する" onclick="notify('ひまか？', '<%= task_path(@task) %>')"/>